### ISSUE TITLE
out-of-date bogus repo ?

### ISSUE THREAD

**Issue by igouy** [vyzo/lisp-benchmarks-game#1]
These were [removed deliberately](https://salsa.debian.org/benchmarksgame-team/archive-alioth-benchmarksgame/-/blob/master/contributed-source-code/benchmarksgame/README)  because we figured out they were a bad idea:

chameneosredux		obsolete
fastaredux			obsolete,removed
meteor				obsolete
regexdna				obsolete,removed
threadring			obsolete

Here are [the Lisp programs](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/lisp.html)  shown on the benchmarks game website.

Here are [the Racket programs](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/racket.html).

Here's [the **benchmarks game** website](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html).

**Comment by vyzo** [comment]
It is not bogus. I took what I found to work with, I couldn't find the up to data programs in the site repo and I hate working with gitlab.

Thank you for pointing me to the right direction; I will update the programs and remove the obsolete ones.

**Comment by vyzo** [comment]
Can you point me to the programs for C and Go?

**Comment by vyzo** [comment]
I can also contribute the gerbil programs when I am done bumming them.

**Comment by vyzo** [comment]
> Can you point me to the programs for C and Go?

Ok, I found them.

**Comment by vyzo** [comment]
See #2, I have updated for the latest and greatest programs from the official site.

So, not bogus; just unofficial and a vehicle for me to push the envelope in gerbil performance.
